# Pre-Design :Stakeholder Information and preferences
In this notebook the stakeholders of the project can be defined and their preferences for the design can be recorded for further processing in the schematic design and configuration stage of the methodology 

## Initilization
Libraries used in this notebook :<br/>
1.Topsis for MCDA [https://pypi.org/project/topsis-jamesfallon/]<br/>
2.Ipywidgets for interactivity [https://minrk-ipywidgets.readthedocs.io/en/latest/index.html]<br/>

In [1]:
import os
import sys
import topogenesis as tg
import pyvista as pv
import trimesh as tm
import numpy as np
from topsis import topsis as ts
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual , Layout
import ipywidgets as widgets
np.random.seed(0)
np.set_printoptions(threshold=sys.maxsize)

### Define Widget styles

In [2]:
layout = widgets.Layout(width='auto', height='auto') #set width and height
style = {'description_width': 'initial'} # Display full text

## Define the Stakeholders of the Project

 Define the number of Stakeholders and their name in the project by editing the widgets in the notebook

In [3]:
Stakeholder_number_widget = widgets.BoundedIntText(
    value=1,
    min=0,
    max=10,
    step=1,
    description='Number of Stakeholders:',
    style=style,
    disabled=False
)

In [6]:
Stakeholder_number_widget

BoundedIntText(value=4, description='Number of Stakeholders:', max=10, style=DescriptionStyle(description_widt…

In [7]:
Stakeholder_number = Stakeholder_number_widget.value
Stakeholder_numbering = []
for s in range(Stakeholder_number): 
    a= "Stakeholder"+ str(s+1)
    Stakeholder_numbering.append(a)

### Input the name for the Stakeholders in the tab widget

In [8]:
tab_contents = Stakeholder_numbering
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab

In [9]:
Stakeholder_list = []
for i in range(len(children)):
    Stakeholder_list.append(tab.children[i].value)

In [10]:
print (Stakeholder_list)

['person1', 'person2', 'person3', 'person4']


In [11]:
Stakeholder_dropdown = widgets.Dropdown(
    options= Stakeholder_list,
    value= str(Stakeholder_list[0]) ,
    description='Number:',
    disabled=False,
)

## Define the stakes of the stakeholder in the project 

In [ ]:
## To be done at a later Stage

## Select the stakeholder for recording design preference

In [12]:
Stakeholder_dropdown

Dropdown(description='Number:', options=('person1', 'person2', 'person3', 'person4'), value='person1')

## Selection of appropriate Design criteria 

The appropriate design criteria should be selected for each stakeholder to create a design preference which is a collection of various simulation lattices calulated for the site

In [13]:
Stakeholder =str(Stakeholder_dropdown.value)

In [14]:
Design_criteria_selection=widgets.SelectMultiple(
    options=['Solar Access', 'Solar Envelope', 'View from street','View to IJ', 'Quiteness', 'Closeness to facade N', 'Closeness to facade S', 'Closeness to facade E','Closeness to facade W','Closeness to Roof', 'Closeness to Ground','Sky View'],
    value=['Solar Access'],
    rows=12,
    Stakeholder = "a",
    description=f'Design Criteria for {Stakeholder}',style = style,
    disabled=False,
    layout = layout
)

In [16]:
Design_criteria_selection

SelectMultiple(description='Design Criteria for person1', index=(1, 2, 3, 4, 5), layout=Layout(height='auto', …

### Selection of appropriate Weights for the Design Criteria

In [17]:
def criteria_slider(name):
    criteria_slider=widgets.IntSlider(   
    value=5,
    min=0,
    max=10,
    step=1,
    description=str(name),
    style=style,
    layout=Layout(width='500px'),
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d')
    return criteria_slider

In [18]:
slider_lists=[]
for a in (Design_criteria_selection.value):
    slider_lists.append(criteria_slider(a))

In [19]:
ui = widgets.GridBox(slider_lists,layout=widgets.Layout(grid_template_rows="auto"))
display(ui)

GridBox(children=(IntSlider(value=5, continuous_update=False, description='Solar Envelope', layout=Layout(widt…

In [21]:
print (ui.children)

(IntSlider(value=7, continuous_update=False, description='Solar Envelope', layout=Layout(width='500px'), max=10, style=SliderStyle(description_width='initial')), IntSlider(value=8, continuous_update=False, description='View from street', layout=Layout(width='500px'), max=10, style=SliderStyle(description_width='initial')), IntSlider(value=7, continuous_update=False, description='View to IJ', layout=Layout(width='500px'), max=10, style=SliderStyle(description_width='initial')), IntSlider(value=7, continuous_update=False, description='Quiteness', layout=Layout(width='500px'), max=10, style=SliderStyle(description_width='initial')), IntSlider(value=7, continuous_update=False, description='Closeness to facade N', layout=Layout(width='500px'), max=10, style=SliderStyle(description_width='initial')))


In [24]:
Topsis_weights =[]

for slider in  ui.children:
    Topsis_weights.append((slider.value)/10)

print(Topsis_weights)

[0.7, 1.0, 0.7, 0.5, 0.7]


### Importing all the necessary Lattices into the Notebook

It is necessary to flatten the matrixes for combining and MCDA

#### Import the Solar Access from csv

In [25]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [26]:
Solar_Access_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Solar Envelope matrix from csv

In [27]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [28]:
Solar_Envelope_matrix = np.random.randint(1, 9, (10), dtype='l')

In [32]:
#print(Dummy_Solar_Envelope_matrix)

#### Import the View from street matrix from csv

In [33]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [34]:
View_from_street_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the View to IJ matrix from csv

In [35]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [36]:
View_to_IJ_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Quiteness matrix from csv

In [37]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [38]:
Quiteness_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to facade N from csv

In [39]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [40]:
Closeness_to_facade_N_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to facade S from csv

In [41]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [42]:
Closeness_to_facade_S_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to facade E from csv

In [43]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [44]:
Closeness_to_facade_E_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to facade W from csv

In [45]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [46]:
Closeness_to_facade_W_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to Roof from csv

In [47]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [48]:
Closeness_to_Roof_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Closeness to Ground from csv

In [49]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [50]:
Closeness_to_Ground_matrix = np.random.randint(1, 9, (10), dtype='l')

#### Import the Sky View from csv

In [51]:
#lattice_path = os.path.relpath('Voxelized_base_lattice.csv')
#Solar_access_lattice = tg.lattice_from_csv(lattice_path)
#Flatten Solar_access_lattice

In [52]:
Sky_View_matrix = np.random.randint(1, 9, (10), dtype='l')

In [53]:
print(Sky_View_matrix)

[8 8 6 6 6 1 2 6 2 4]


In [54]:
#Dictionary Values
Matrix_names_from_imported_lattices = [Solar_Access_matrix,Solar_Envelope_matrix,View_from_street_matrix,View_to_IJ_matrix,Quiteness_matrix,Closeness_to_facade_N_matrix,Closeness_to_facade_S_matrix,Closeness_to_facade_E_matrix,Closeness_to_facade_W_matrix,Closeness_to_Roof_matrix,Closeness_to_Ground_matrix]
# Dictionary Keys
Matrix_names_in_widget =['Solar Access', 'Solar Envelope', 'View from street','View to IJ', 'Quiteness', 'Closeness to facade N', 'Closeness to facade S', 'Closeness to facade E','Closeness to facade W','Closeness to Roof', 'Closeness to Ground','Sky View']

In [55]:
Dict_of_lattices = {} 
for key in Matrix_names_in_widget: 
    for value in Matrix_names_from_imported_lattices: 
        Dict_of_lattices[key] = value 
        Matrix_names_from_imported_lattices.remove(value) 
        break  

In [56]:
#print(Dict_of_lattices)
retrieved_lattices = [Dict_of_lattices[x] for x in Design_criteria_selection.value]

In [57]:
flipped_lattices= np.transpose(retrieved_lattices)

List_of_lattices_for_Topsis=[]
for r in flipped_lattices:
    print(r)
    List_of_lattices_for_Topsis.append(np.ndarray.tolist(r))

[6 2 3 1 4]
[3 5 4 2 7]
[5 4 1 2 4]
[8 1 2 2 3]
[7 4 4 8 8]
[1 6 6 1 5]
[1 7 4 8 3]
[5 8 4 3 1]
[3 8 7 5 1]
[2 1 8 8 5]


In [58]:
print(List_of_lattices_for_Topsis)

[[6, 2, 3, 1, 4], [3, 5, 4, 2, 7], [5, 4, 1, 2, 4], [8, 1, 2, 2, 3], [7, 4, 4, 8, 8], [1, 6, 6, 1, 5], [1, 7, 4, 8, 3], [5, 8, 4, 3, 1], [3, 8, 7, 5, 1], [2, 1, 8, 8, 5]]


### Select the Cost and benefit for the design criteria

In [72]:
def Radio_widget(text):
    Radio_widget = widgets.RadioButtons(
    options=['Cost', 'Benefit'],
    value='Cost',
    description=str(text),
    disabled=False,
    style=style,
    layout=Layout(width='500px')
)
    return Radio_widget

In [73]:
Radio_lists=[]
for a in (Design_criteria_selection.value):
    Radio_lists.append(Radio_widget(a))

In [100]:
ui_radios = widgets.GridBox(Radio_lists,layout=widgets.Layout(grid_template_rows="auto"))
display(ui_radios)

GridBox(children=(RadioButtons(description='Solar Envelope', index=1, layout=Layout(width='500px'), options=('…

In [101]:
Topsis_I =[]

for radio in ui_radios.children:
    if radio.value == "Cost":
        Topsis_I.append(0)
    else:
        Topsis_I.append(1)

print(Topsis_I)

[1, 1, 0, 1, 0]


### Topsis for MCDA

In [104]:
a = List_of_lattices_for_Topsis
w = Topsis_weights
I = Topsis_I
decision = ts(a, w, I)
ghr = decision.calc()

print(decision.C)

[0.45176314 0.40462126 0.55492577 0.5090963  0.50387407 0.40259208
 0.58285082 0.70229015 0.59897634 0.30069722]


### Vizualise the decision matrix for the user 

### Reshape the lattice to original lattice 

### Save the User preference lattice as CSV
The lattice for the selected Stakeholder will be saved as Csv Continue this process for all the users and make the lattices for all of them 

### Save the Stakeholder Influence as a CSV
The information of the stakeholders and their stakes in the various items from the space program will be saved in a csv