In [1]:
import numpy as np
import topogenesis as tg


In [46]:
class agent ():
    def __init__(self,ind):
        self.origin = np.array(ind).astype(int)
        self.old_origin = self.origin
    def walk (self,step):
        self.old_origin = self.origin
        self.origin += step

In [47]:
np.random.seed(0)
unit = 1
bounds = np.array ([[0,0,0],[0,7,7]])
my_lattice = tg.lattice(bounds,unit=unit,default_value=1, dtype=int)
#print(my_lattice)

selected_cells= np.random.choice(my_lattice.size,5)
#print (selected_cells)

agent_ind = np.array(np.unravel_index(selected_cells, my_lattice.shape))
print (agent_ind)

[[0 0 0 0 0]
 [5 5 6 0 0]
 [4 7 5 0 3]]


In [58]:
agents= []
for ind in agent_ind.T.tolist():
    my_agents = agent(ind)
    agents.append(my_agents)
    
for a in agents:
    step=np.array([0,0,1])
   # a.walk(step)
    print (a.old_origin,a.origin)

[0 5 4] [0 5 4]
[0 5 7] [0 5 7]
[0 6 5] [0 6 5]
[0 0 0] [0 0 0]
[0 0 3] [0 0 3]


In [59]:
class enviornment():
    def __init__(self,lattice,agents):
        self.availability = lattice
        self.agents = agents
    def update_availability (self):
        for a in self.agents:
            self.availability[tuple(a.origin)] = 0 

In [62]:
env = enviornment(my_lattice, agents)
#print (env.availability)
env.update_availability()
print (env.availability)

[[[0 1 1 0 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1]
  [1 1 1 1 0 0 1 0]
  [1 1 1 1 1 0 1 1]
  [1 1 1 1 1 1 1 1]]]
